language: python
python:
- '3.5'
env:
  global:
  - TRAVIS_NODE_VERSION="6.9.1"
  - MEERKAT_AUTH_SETTINGS="/home/travis/build/meerkat-code/meerkat_auth/auth.cfg"
  - secure: "nmSptg1wlK+rPwtyGLH/TtUXj+rVX1PRchq1SagRdvNuQZ0OkR31/WlanBgVjkJ8TJok9prjX9NeC4KV4a6lvXi4G0pp3yrRnmV6wEoruwMcad5dMt6E+fI+eIE5MfA5zAE2WepvMQPj7mHyl6wCswdEgVJdJmau5H/pFv7XU5pyWz+Aon2IHxMt6Q6bcc7X8sYSXj11IWV82vrHdSzveVKpCI/FNT1u2n2af6AWsM/xrPYYcYoigYhx3g06LHopJVHyZUg607MLa5qA7QZiu17eP48hil4SaMKfTmwt2wQstwmEHTc7BeXjIQ4AdRW89b42YVet/qqDcdyF0Wx2EPk7ZAw91YczQLccu/BKlL/any/J+KKADlAhDU2owu11L4TOWo7DWIzKDOHN4XXzIhapc6sKcHxWIhdOh0xEs5g8EoTnnbOSEM/pDuIThOcd7Fu2whud4ADqb4BTSSnhGY1t3YfrN6iHVPY2EMRIMVj2om4cSknMkoRCi626H8QALmW4imY7JsLgj9s3vrU+Dj9Fr0km57G/JRHXlK7camGj0jYeQpeZjMCZLgFTJotb4eo98JQAewd6rwaF5cmPJ8AyGyJLtyZqDgT0f//PKgsAu47qJReNHMuejiay+EImD3tk4F5ZsGKJv+r2KoSlVLDqTF6GMzns/obNw9cP3kQ="
  - secure: "n82SQ+FRlTx//7ldUkkUVKJ4JYF/txFRnf9E5QqRHrEH+TaBeRl0Stg3jC+B2gxcpCes89AXm5k/cfdOM2wHPwC3gUDVkqumPtIHtPWXJQ5eWoB0NrRZPDfVD8y3FBP2PvwUBcqIU5Slu88njIZmUtdtTnLNEXX68zSDjwyVsE0f+HE69cu2SEiyNsgWZwooEwdLK7cYwB70IK4giph4cRM+7bzZ3mjhBO88PqEEcQJkXpWjI0RX20AsAufmRphLJhOM+9gwbX9zeJQTP/OajGC7gY4ZBQMU3nBYfj65VgS+wdomKEEKOPZKa9gWrtL9bUc1CvhnLpCSzC0ccowgI6m8eqTlBTO9YrBNxKWx1zp/1Ry7TLns1/RVgj+KsaoNyjmlEELj7kT0CjfAEjcVFbf6vbipwkMRkNDLYtThni181So/++DXTTY3tZ7E/reERenLDCSUIfVasqQ5czr9KY4YB4xjIHQwGt/XpNvK9v+3kFeQTbl4FKtopXTbfk5jcmM2+wqck7xmCzJfsHjGL0XIVelwMNu/DViXBaQ5psHavmRRPFuuyvUrnPk5saGzit8c+JX65tB4Wp/UjjWd9cprrg5OeKiQGyB9hsEw2wKzJ8wpzuQ9voqEjxyigfUdvPr5rXjQwtO4KkOzuIqzXcT1c98FKXshVE2cVCxalsw="

install:
- pip install .
- pip install -r requirements.txt
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- npm install -g yarn
- yarn install
before_script:
- bower install
- gulp
script: nosetests --logging-level=WARNING
notifications:
  slack:
    secure: ppa6rHIFl9IuPV2l7yg53PrSWEbOyIW9A9ySOSfZgXt10tAQVEXBk1+uWQXYy06dYvH8iZvhZz/kXnQsIq2cka4W0ZzY4k6DROQROdkc4svANcO6d8A2AdGmhrltMzLCRYuaPGl4aMaOLIPtAb7e+Qw1qY6Te23vn8Cl1teKKneBFod71pDT+kn9bxUS/D7+Rn9kMosQfyShSgBbA3jifIr7D9612okphbFqVciqcbX5hiL9AZ7MNHrvhCbTBV+igsiEyWRYsGBZqyg4f6chhz7plb1Z9RJsJcqm5jHgLquyOZZgQ2ugYcbiVO8kxWQi4dfuYiaQd4Q1/vHa3YviIAw+sCdsd/p8CSivdrZhCUoUo1A8Z4Wmiw5ve7cvbOv2nzTTizwUDWI1ATBun0KhoZFyrpSQHkjYxQej5UQhobc9aLcI3vxFyq7BDD2pz3pw+u/LCLUBpyiWW/5IfF3BCFanr6Am3lQ1J2nT80sc8Fl5tyUadeFTO61W6pL1OcLycCg98X5ig+sen++J6eog2swGacFJK12EoNMlCAxV77aba5wVvupVdeBcN8zRKeWrBkr1d9kIXAbRrH8hrrejilk+602l06TRCsUGEFvO3/eKIoQxVsIftaOOnBCu3J5Q9sd2AHVOtRMcp7KhQ1KYv4tmNzU6DFTm0ilsBBcR3ts=
