language: python
python:
- '3.5'
env:
  - TRAVIS_NODE_VERSION="0.12"
  -  MEERKAT_AUTH_SETTINGS="/home/travis/build/meerkat-code/meerkat_auth/auth.cfg"
  -  secure: "pv8gR7tqiNsosBlKLOvT5B6KqadquuySJchz79XDgFm65YpV6M8CPm3BuksyVp/lF3xBL2OjbGnTykcrXjkQzR32u2UD4oQmZIPGqTyXySN7dMxTz4TGhhfUq/AwGnRbzqpaKyaDKrUEnKlixMWsaJhFOSK5iyjRmIzAtF2yGf9RagjrcB2Irn5qh//uPXvrjXrMo1AMAFwqYZYdprupmZRYVJDQ8Q0cWbtBYxlwhdQOiXvsx9dcNYKFd3PvThV7fe1rlEZRTXvDZ17MwR3Q0RCNxG6ORsjwzbzZxvECGV/s3+nDD4YTQMAcWZi9SolShz/ui/8l/Cz4KOlTvmfF7+DyCSECMxOTXPqcgft5AxMMJFBdkST7JShVrfVE8rNx2Oj3zoooiP/XWNWmfFwFSIwfv+RVHbaBi1FjIHl50mm68FHccumHhZ7+EFhDCzvor0er1q+KTF8+9rB9DjLqJibRFsLdXgxUNoJlDv661slkFL3KQjV2Iri12YDYlPfn0lZENGm8xCRL8e8XbvVRU5cMg1Oq1nsihZlnmq7efd+vA1m6MAZ8zG/2ygtcGEhJLmS9f9hdUBgYiD9qAahb5gazPHUcbITatZk3pNQDBcfNLW4CXGJIPWEd1snp4PbcArxj8NhBpNqsCt6E87s9SxVfslbRGvuDgt04IFZOq6o="
  - secure: "TscpNmmJ8zxGH6L51iHjjFAaOceSzDRk2vqZBNknYiZNKnldw0lAa+4MWkLlWxWi52+fTgEK3QovnAnJgtzvK2NJPycPc6SqiiytKirFnQj8KI4MsgIS/xaLaAJbzIvf5oBkz9ghVSr95jpUM/02lgpx5b98Z5eZjmMIy6ZhnSgmeQtK4RJyAnzfh3KE0KGLJ9xsOGnVd3d/f7hzl5TxXNkcPQ3plL5TcR66NbSORivX+fheXTFvS3a1Jq2Jln5cdQ9StorVxyPjjauirkG9ji3CCITpJ3pw2FcBBwbX5NXT/1QQkfuUdCd401TEgqKCHW6I7UjV8vseg2fEMYoM1Z/pFt+TcFh2niTKFlnSx5vE0xDlLX61mrST7EJ5OWs9GIyX0C4kEHkQtfXLjG+qvseqsshrhH49hREfuD2We7VJab/iAHUTtAqdHAn8Fl0QDhzF34kZgai8oLEduoP4Eac0sYr0GrTGjmW3nVvSvRFH4Ei/tLiAAHbeuMYNNaIOUaMcCbD9MJTBGdQdRoaOwMY2GoTiO3wqpb0NlDVvwq+HZm9AmoEnOnhis/DYFXLlrJEffXA4g220X1eV3Q2rp/Rka/khWO1lsTDgsq6KlGIHvvXhWlOB7Bid06F0G0anCv4GKqIvAvEn3UiFyME76n5TpWzpsz9erKakp6uqE3A="

install:
- pip install .
- pip install -r .travis-requirements.txt
# As per http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install

before_script:
- bower install
- gulp
script: nosetests
notifications:
  slack:
    secure: JAyJidj1nalEoJhp7JL22tabEXn1xBl6MXQOnP6pratbVyz/haWuDh7OQGZxf0kXO1zaKu6k9A4zQZKr0LiKeUT1Xx5kdeP8C9NzZrYtf6IKLw50HhTq7OhnQ9PtdR2DQ+uT1PcudQWNOeq8+0Yu3aTD/nBH626Gp7qQqRhuX3vUYZs1V05mmxbIrND2OtjR69UkIWwnzFzJDsJCbjY5PojPtfQ1lDlXwulkNV66RfJnJYeWf0ndBgCnEff6OXJ993oUcCWHEsQP5HdgR2IEnyuXHzgjiAnc+M6C4Xes/uS1FEOlwVvpkvysx+FvbQl+SEet+9ottakp5P8QjSKG4159L0Po3n2AISfIcZgMSVuCkIF9mHl23vo8Sb0LdoliHSZhbRP05spAioxf0cfBLBa3isMV2Ur7/BhHjc9Tjxs+obLdJmPRzcch1bYWePFDVJySA57nZUR0CdvObl0h+he+ye5z9/MkfRvHN+kUXkOb5tI+CY1n76vjqoVT6AUagA3Vpsn8Q3dQKhd4JmXg70NeEgM9M0Msql2TDCtEVvk47twEQrlQXCOjGU1B/JJ9l98qQdF3YkuS1vSbjXXZnFYHDg0M6vSddmFhVADfflATbM2pU7v7jdBpTbJxL9rz75Lf535Dk0haM1IWeafmnZhrddq5qrj5+qqsFHmA/ww=

